[Context]
Namespace = "example"
Name = "example-server"
ID = 1001

[Context.R]
HTTPServer = "httpserver"
EventSystem = "eventsystem"

[[Components]]
Name = "github.com/gopherd/example/components/logger"

  [Components.Options]
  Level = "DEBUG"
  Output = "stdout"

[[Components]]
Name = "github.com/gopherd/example/components/eventsystem"
UUID = "{{ .R.EventSystem }}"

  [Components.Options]
  Ordered = true

[[Components]]
Name = "github.com/gopherd/example/components/auth"

  [Components.Refs]
  HTTPServer = "{{ .R.HTTPServer }}"
  EventSystem = "{{ .R.EventSystem }}"

  [Components.Options]
  Secret = "{{ .Namespace }}-secret"

[[Components]]
Name = "github.com/gopherd/example/components/users"

  [Components.Refs]
  HTTPServer = "{{ .R.HTTPServer }}"
  EventSystem = "{{ .R.EventSystem }}"

  [Components.Options]
  MaxUsers = 1000

[[Components]]
Name = "github.com/gopherd/example/components/httpserver"
UUID = "{{ .R.HTTPServer }}"

  [Components.Options]
  Addr = ":{{ add 8000 .ID }}"

[[Components]]
Name = "github.com/gopherd/example/components/blockexit"
